### ISSUE TITLE
Write README guidelines

### ISSUE THREAD

**Issue by SamuelBeaurepaire** [SRGSSR/guilde-plateformes-propres#1]
**As an RTS developer** I need guidelines how to write overview documentation for a project. The goal is that any developer, from RTS, SRG SSR or external, arriving on the GitHub project landing page can quickly understand the purpose of the project, how they can run it and how they can contribute to it.

# Acceptance criteria

- A readme guideline file is available.
- The guidelines are written in English so that any developer have a chance to understand them.
- Guidelines include a set of bullet points that developers should follow when creating the README for their own projects.

# Tasks

- [x] Discuss obvious readme content within the guild.
- [x] Have each guild member look at other projects for inspiration.
- [x] Write the specifications.

**Comment by SamuelBeaurepaire** [comment]
Here are some ideas of what could be in those guidelines:
- Written in English
- Should be concise
- Brief summary of what the project does
- Contribution guide link
- Quick start guide
- Any other documentation link
- License link
- Links to the online products themselves if available (web link, App Store / Play Store, etc.)

**Comment by defagos** [comment]
Some additional _should have_ bullet point proposals:

- A product logo if available. Not only nice to see but also allows user to quickly associate a product with a visual identity.
- A screenshot for front-end oriented products. A picture is worth a thousand words.
- Badges (e.g. build status, code coverage, etc.).

There is also no need for a table of contents, GitHub automatically generates one, available from a dedicated button at the top right of the readme file.
