### ISSUE TITLE
Write a guide to meet the Community Standards

### ISSUE THREAD

**Issue by jboix** [SRGSSR/guilde-plateformes-propres#2]
**As an RTS developer** I need guidelines on how to meet the [Community Standards](https://github.com/SRGSSR/guilde-plateformes-propres/community) criteria of my GitHub repository.

## Acceptance Criteria 

- Detail how developers can navigate to `Insights` > `Community Standards` in their GitHub repository and provide a short description of each category.
- Provide standard templates and resources to facilitate the developer task of meeting these categories, for example:
  - A `Code of Conduct` template.
  - A `Contributing Guideline` template.
  - Out of scope: Security policy, see #3.

## Tasks

- [x] Discuss which templates to provide with the guild.
- [x] Write the guide.
- [x] Apply the guide to this repository.

**Comment by defagos** [comment]
- An [example](https://www.contributor-covenant.org/version/2/1/code_of_conduct/) of a Code of Conduct template.
- An [example](https://github.com/SRGSSR/pillarbox-apple/blob/main/docs/CONTRIBUTING.md) of Contributing Guidelines.
- Link to some issue / PR template ideas since those will likely be specific to a project.
- Link to [license chooser](https://choosealicense.com/).
