### ISSUE TITLE
Write Technical Documentation Guidelines

### ISSUE THREAD

**Issue by jboix** [SRGSSR/guilde-plateformes-propres#4]
**As an RTS developer** I need guidelines to provide Technical Documentation within my project.

## Acceptance criteria

- Define the documentation levels, e.g.: API Documentation, Integration guides, Architecture Diagrams, Specifications...
- Define the preferred channel of each level of the documentation, e.g.: `Architecture Diagrams should be available through the Wiki`, `API Documentation should be available within the code`...
- Define the best practice for writing the documentation, e.g. : `Describe what a method does instead of how it is implemented`, `Provide code samples`....
- Provide tools to enhance the documentation interaction, e.g. : `Swagger`, `DocC`....
- Create a section in the deployment documentation detailing the procedure for tagging:  applications in AWS and other deployment services. Specify that each application must be tagged with the repository name to allow the infrastructure team to easily identify which instances are associated with each project.

## Tasks

- [ ] Discuss the documentation levels within the guild.
- [ ] Discuss the Technical Documentation best practices within the guild.
- [ ] Produce the guideline.
